### ISSUE TITLE
Application and Infrastructure metadata

### ISSUE THREAD

**Issue by kartshy** [SODALITE-EU/application-optimisation#3]
Discussed in the Performance modelling meeting about the Application and Infrastructure metadata. 
Need metadata about infrastructure and Application to be stored. This information is obtained by the Discovery plugin and added by Resource expert and  AoE. 
The plan to store them in IaC model repository.

**Comment by kartshy** [comment]
Need to identify the metadata required and find out what metadata is available.
For example, for application optimisation, we need to know the number of nodes, number of GPUs per node, availability of SSDs etc... 

https://docs.google.com/document/d/1tk9ZlG6x7cBWL2WF_YmhFNBxStdhsUjwfd-1YO5BncM/edit#heading=h.7b3j9oxgzd34
has details of the available info.

**Comment by kartshy** [comment]
@kmlTE  For the HPC, I think we can get the following info,

Queue
ntype
num_nodes
Memory
cpuclock
Cpus
Ngpus
gpu_type
Sockets
numa_nodes
Cores
threads

based on the document. We usually have a queue name and dont care about the node names! 
Queue is a group of nodes of the same type. Please let me know if you need more info. For the testbed a default queue is enough.

**Comment by kartshy** [comment]
@rosogon  Can we get similar info from Cloud testbed?

**Comment by kartshy** [comment]
First draft of infrastructure dsl 
I based the hpc on slurm and pbs, cloud on aws, and imagiend Edge
```
{
  "infrastructure":
  {
    "target_type":"hpc/cloud/edge",
    "hpc":{
      "hlrs_testbed":{
        "user_id":"temp",
        "host_name":"sodalite-fe.hlrs.de",
        "ssh_key":"",
        "queue":{
          "name":"batch",
          "availability":true,
          "state":"resolv/alloc/idle",
          "timelimit":45983759834,
          "nodelist":"node1,node2,node3",
          "n_nodes": 5,
          "features":{
            "cpu":"BW18",
            "memory":"256GB",
            "ssd":true,
            "gpu":"volta"
          },
          "hw_info":
          {
            "memory":256,
            "cpu_clock": 2.2,
            "n_cpus": 32,
            "threads_per_core": 2,
            "sockets":2,
            "numa_nodes": 2,
            "n_gpu":1
          }
        },
        "queue1":{
          "name":"batch",
          "availability":true,
          "state":"resolv/alloc/idle",
          "timelimit":45983759834,
          "nodelist":"node1,node2,node3",
          "n_nodes": 5,
          "features":{
            "cpu":"milan",
            "memory":"256GB",
            "ssd":true,
            "gpu":"amdgpu"
          },
          "hw_info":
          {
            "memory":256,
            "cpu_clock": 2.2,
            "n_cpus": 32,
            "threads_per_core": 2,
            "sockets":2,
            "numa_nodes": 2,
            "n_gpu":1
          }
        }
      }
    },
    "cloud":{
      "atos_cloudtestbed":
      {
        "user_id":"temp",
        "host_name":"aws",
        "ssh_key":"",
        "instance1":
        {
          "family":"General purpose",
          "type":"t2.nano",
          "vcpus":2,
          "memory":1,
          "storage":"lustre",
          "network":"5G",
          "ipv6_support":true,
          "n_instance":2,
          "features":{
            "cpu":"BW18",
            "memory":"256GB",
            "ssd":true,
            "gpu":"volta"
          },
          "hw_info":
          {
            "memory":256,
            "cpu_clock": 2.2,
            "n_cpus": 32,
            "threads_per_core": 2,
            "sockets":2,
            "numa_nodes": 2,
            "n_gpu":1
          }
        }
      }
    },
    "edge":{
      "vehicle_inference":
      {
        "user_id":"temp",
        "host_name":"123.12.12.1",
        "ssh_key":"",
        "instance1":
        {
          "name":"batch",
          "availability":true,
          "state":"resolv/alloc/idle",
          "timelimit":45983759834,
          "nodelist":"node1,node2,node3",
          "n_nodes": 5,
          "features":{
            "cpu":"BW18",
            "memory":"256GB",
            "ssd":true,
            "gpu":"volta"
          },
          "hw_info":
          {
            "memory":256,
            "cpu_clock": 2.2,
            "n_cpus": 32,
            "threads_per_core": 2,
            "sockets":2,
            "numa_nodes": 2,
            "n_gpu":1
          }
        }
      }
      
    }
  }
}
```

**Comment by kartshy** [comment]
The idea is these dsl will have all the information required for us to

1. connect to the target (userid, ip)
2. Run the infrastructure and application performance models (need all  instances or queues)
3. Optimise the application deployment (need hardware info and availability of GPU, SSDs)

So the dsl should include all available options that we can run on

**Comment by dev-zero** [comment]
I've decided to go for a simple representation including only elements for which we have direct use at the moment with some possibilities to extend the schema if needed. An example reads like this:

```json
{
  "name": "testinfra",
  "disabled": null,
  "description": "some descr",
  "configuration": {
    "scheduler": "slurm",
    "storage": {
      "file:///scratch": {
        "storage_class": "default-high"
      },
      "file:///data": {
        "storage_class": "default-common"
      }
    },
    "partitions": {
      "mc": {
        "nnodes": 100,
        "node": {
          "ncpus": 2,
          "cpu": {
            "arch": "x86_64",
            "microarch": "zen2",
            "ncores": 64,
            "nthreads": 2
          },
          "naccel": 0,
          "memory": "512GiB"
        }
      },
      "gpu": {
        "nnodes": 5,
        "node": {
          "ncpus": 1,
          "cpu": {
            "arch": "x86_64",
            "microarch": "zen2",
            "ncores": 32,
            "nthreads": 2
          },
          "naccel": 2,
          "accel": {
            "type": "gpu",
            "model": "P100"
          },
          "memory": "256GiB"
        }
      }
    }
  }
}
```

... the cloud case can be handled with a default partition. In contrast to my previous design I've added the possibility to add a storage spec to all of the following levels: infrastructure, partition, node. This makes the `shared` attribute for a single storage location pointless and clarifies whether or not a storage location is shared between which components of the system (when specified on the infra level this is available on all nodes, when specified on the partition then one can assume it is only available for compute nodes, when specified on a node level it is node-local).
With this I expect that we can describe most infrastructures quiet accurately (up to relevant level for MODAK).

At the moment this schema is used to guide the requests at the `/infrastructure` endpoints. Whether or not (and which parts of it) may have to be specified as part of the `/optimization` requests can be discussed in tomorrows meeting.

Also, credentials, runtime attributes and parameters for which we do not have an immediate use were left out deliberately. The same goes for more software-related configurations like the `queue` concept (including associated parameters like the walltime limit) or any connectivity information (since other components within Sodalite will be responsible for that).
